"""Mapping between Bitext intents and CRM MCP tools."""

INTENT_TO_TOOL = {
    "cancel_order": {"tool": "cancel_order", "params": ["order_id"]},
    "track_order": {"tool": "get_order_status", "params": ["order_id"]},
    "change_order": {"tool": "modify_order", "params": ["order_id", "changes"]},
    "place_order": {"tool": "create_order", "params": ["product_id", "quantity"]},
    "delivery_options": {"tool": "get_delivery_options", "params": ["address"]},
    "delivery_period": {"tool": "get_delivery_estimate", "params": ["order_id"]},
    "change_shipping_address": {"tool": "update_shipping_address", "params": ["order_id", "new_address"]},
    "get_refund": {"tool": "process_refund", "params": ["order_id", "reason"]},
    "return": {"tool": "initiate_return", "params": ["order_id", "items"]},
    "check_refund_policy": {"tool": "get_refund_policy", "params": []},
    "create_account": {"tool": "create_account", "params": ["email", "name"]},
    "delete_account": {"tool": "delete_account", "params": ["account_id"]},
    "edit_account": {"tool": "update_account", "params": ["account_id", "fields"]},
    "switch_account": {"tool": "switch_account_type", "params": ["account_id", "new_type"]},
    "recover_password": {"tool": "reset_password", "params": ["email"]},
    "check_payment_methods": {"tool": "get_payment_methods", "params": []},
    "payment_issue": {"tool": "report_payment_issue", "params": ["order_id", "issue_type"]},
    "wrong_item_delivered": {"tool": "report_wrong_item", "params": ["order_id", "description"]},
    "contact_customer_service": {"tool": "get_support_contact", "params": []},
    "contact_human_agent": {"tool": "escalate_to_human", "params": ["reason"]},
    "complaint": {"tool": "submit_complaint", "params": ["subject", "description"]},
    "review": {"tool": "submit_review", "params": ["order_id", "rating", "comment"]},
    "newsletter_subscription": {"tool": "manage_newsletter", "params": ["email", "action"]},
    "check_cancellation_fee": {"tool": "get_cancellation_fee", "params": ["order_id"]},
    "get_invoice": {"tool": "get_invoice", "params": ["order_id"]},
    "check_invoice": {"tool": "get_invoice", "params": ["order_id"]},
    "track_refund": {"tool": "track_refund_status", "params": ["order_id"]},
}
